開催者タスク例の作成
aws-samples/aws-ml-enablement-workshop pull request #26
Opened 2022-11-22 03:09 UTC by littlemex

*Issue #, [#25](https://github.com/aws-samples/aws-ml-enablement-workshop/issues/25)

*Description of changes:*

開催者タスク例を作成した。

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-11-22 03:10 UTC, littlemex commented
@icoxfog417 開催者側のタスク例を作成したのでレビューお願いいたします。

2022-11-22 05:27 UTC, icoxfog417 requested changes
コメントしました！

2022-11-22 05:27 UTC, icoxfog417 commented on docs/organizer/tasks.md
> +イベント開催者に向けて イベント開催のために必要なタスクの例を提示します。
「ML Enablement Workshopの主催者が行うタスク」と、主語を明確にするのはどうでしょう。
微妙な修正ですが、イベントの開催⇒ワークショップの開催、のほうがわかりやすいかもです(このリポジトリ自体に「ワークショップ」とついているので)。

別件ですが、README.mdのライセンスの箇所に「AWS以外の個人や法人が、AWSの許諾なしに本GitHubの教材を使い「ML Enablement Workshop」または同一とみなされる表記でワークショップを提供することはできません。今後、より開催者の間口を広げられるよう準備を進めていく予定です」と記載しておこうと思います。

2022-11-22 05:27 UTC, icoxfog417 commented on docs/organizer/tasks.md
> +
ここで番号を付けたら、以降の説明でもこの番号と順序で説明していくのはどうでしょう。

2022-11-22 05:27 UTC, icoxfog417 commented on docs/organizer/tasks.md
> +# 開催者が実施するタスク例
「ML Enablement Workshopの主催者が行うタスク」と言い切ってよいと思います。

2022-11-22 05:27 UTC, icoxfog417 commented on docs/organizer/tasks.md
> +## 申し込み
「全体の流れ」は主語が開催者の目線で書かれているので、以降も開催者の目線で統一すると良いと思います。
(「申し込み」の場合、主語は参加者になると思います)

2022-11-22 05:27 UTC, icoxfog417 commented on docs/organizer/tasks.md
> +以下の開催要件への同意についてご返信ください。
チェックリストがとてもよくできているので、「メールのテンプレートとしてご利用ください」と書いておくとGOODと思います！

2022-11-22 05:27 UTC, icoxfog417 commented on docs/organizer/tasks.md
> +### AWS 主催の場合の依頼事項
これは見出しでなく、注釈としてそっと書いておく感じでいいと思いました。

2022-11-22 05:27 UTC, icoxfog417 commented on docs/organizer/tasks.md
> +各組織の情報統制とファシリテーション負荷の観点から Day 3 のアイデアソンを合同で実施することは難しいです。
同じ企業の場合は可能なケースもあると思うので、「Day3のアイデアソンはチームごと個別開催が基本です。ただ、チームごとの情報共有が許される場合、ファシリテーターが複数チームをマネジメントできる場合はこの限りではありません」という感じに書くのはどうでしょう?

2022-11-22 05:27 UTC, icoxfog417 commented on docs/organizer/tasks.md
> +以下の情報を記入の上ご返信ください。
メールのテンプレートとして使えるようにするなら、注釈が文面に含まれないようにすると良いと思います。

2022-11-22 05:36 UTC, icoxfog417 commented on docs/organizer/tasks.md
> +    その際にホワイトボードツールとして Miro の利用を前提としてイベントが設計されています。
2.3 [ ] 開発者向けハンズオンのために Studio Lab をご準備頂くことへの同意
    本ワークショップの開発者向けハンズオンでは SageMaker Studio Labで進めることを前提として設計されています。

こちらを入れておきましょうか。企業によってはMiroと同様忌避するケースがあり得るので、事前確認として入れておきましょう。

2022-11-22 09:49 UTC, littlemex commented
@icoxfog417 再度レビューお願いします！

2022-11-22 10:18 UTC, imatsuzaki requested changes
大まかな流れは良さそうですが、一点コメントしました！

2022-11-22 10:18 UTC, imatsuzaki commented on docs/organizer/tasks.md
> +1. 開催日程 (*1)
[nit] markdownの仕様にもよりそうですが、 `[^1]` とかで注釈つくると楽かもです

2022-11-22 10:18 UTC, imatsuzaki commented on docs/organizer/tasks.md
> +## 全体の流れ
この「全体の流れ」って既にMLEWを行えるクライテリアを満たしているのを確認後の流れになりますかね？
もしこのタイミングでクライテリアの確認が必要なら、流れの中に明確に書いちゃっていいと思いました。

特に「PdMが参加しない」「AI/ML人材がいない」みたいな応募が来た時に、開催ができない旨はもう少し強調してもいいかなと思いました！

2022-11-25 07:26 UTC, icoxfog417 commented on docs/organizer/tasks.md
> +イベント開催者に向けて イベント開催のために必要なタスクの例を提示します。
修正確認しました。

2022-11-25 07:26 UTC, icoxfog417 commented on docs/organizer/tasks.md
> +# 開催者が実施するタスク例
修正を確認しました

2022-11-25 07:26 UTC, icoxfog417 commented on docs/organizer/tasks.md
> +## 申し込み
修正を確認しました

2022-11-25 07:26 UTC, icoxfog417 commented on docs/organizer/tasks.md
> +以下の開催要件への同意についてご返信ください。
修正を確認しました。

2022-11-25 07:27 UTC, icoxfog417 commented on docs/organizer/tasks.md
> +### AWS 主催の場合の依頼事項
修正を確認しました

2022-11-25 07:27 UTC, icoxfog417 commented on docs/organizer/tasks.md
> +各組織の情報統制とファシリテーション負荷の観点から Day 3 のアイデアソンを合同で実施することは難しいです。
修正を確認しました

2022-11-25 07:28 UTC, icoxfog417 commented on docs/organizer/tasks.md
> +    その際にホワイトボードツールとして Miro の利用を前提としてイベントが設計されています。
修正を確認しました。

2022-11-25 07:31 UTC, icoxfog417 commented on docs/organizer/tasks.md
> +## 全体の流れ
@littlemex さん、クライテリアについて言及しておきましょうか。`task.md`はタスクのリストにして要件は別のファイルにしてもいいかもしれません。いずれにしても、どこかに書いてあればOKだと思います。

2022-11-30 05:19 UTC, littlemex commented on docs/organizer/tasks.md
> +    その際にホワイトボードツールとして Miro の利用を前提としてワークショップが設計されています。
いつまでに準備が必要かかく。Day1で使うのでDay1当日までに準備してもらう

2022-11-30 05:26 UTC, littlemex commented on docs/organizer/tasks.md
> +# ML Enablement Workshop の主催者が行うタスク
開催者で統一する

2022-11-30 05:36 UTC, littlemex commented on docs/organizer/tasks.md
> +## 全体の流れ
本資料のTOCとして全体の流れと書きましたが無駄に混乱を生みそうなので削除します。クライテリアの確認はMLEW紹介後に同意として必要になるのでその旨書いておきます。

> 特に「PdMが参加しない」「AI/ML人材がいない」みたいな応募が来た時に、開催ができない旨はもう少し強調してもいいかなと思いました！
こちらについては、個別開催の場合は、AWSから提供しないケースではそこを許容して自分達で提供する可能性はあるのでこの文書では明示しないことにします。

2022-11-30 05:39 UTC, littlemex commented
@icoxfog417 再度レビューお願いします。

2022-11-30 05:58 UTC, merged

2022-11-30 05:58 UTC, icoxfog417 commented
OKです。マージしました！